[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"

[[redirects]]
 from = "/about"
  to = "/"
  status = 301

[[redirects]]
  from = "/speaking"
  to = "/"
  status = 301